using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEditor.SceneManagement;

namespace DDOIT.Tools.Editor
{
    /// <summary>
    /// Addressables에 등록된 씬 목록을 기반으로
    /// DDOIT Tools > Scene Switcher 서브메뉴에 MenuItem을 자동 생성한다.
    /// DDOIT 씬은 최상단, InitScene은 그 아래, 나머지 Addressable 씬이 하단에 배치된다.
    /// Addressable 그룹 변경 시 자동 갱신된다.
    /// </summary>
    [InitializeOnLoad]
    public static class SceneSwitcher
    {
        private const string DDOIT_SCENE = "DDOIT";
        private const string INIT_SCENE = "InitScene";
        private const string GENERATED_PATH = "Assets/DDOIT_Tools/Scripts/Editor/SceneSwitcher/SceneSwitcherItems.g.cs";

        static SceneSwitcher()
        {
            EditorApplication.delayCall += RegenerateIfChanged;

            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings != null)
                settings.OnModification += OnAddressablesModified;
        }

        private static void OnAddressablesModified(AddressableAssetSettings settings, AddressableAssetSettings.ModificationEvent evt, object obj)
        {
            if (evt == AddressableAssetSettings.ModificationEvent.EntryAdded ||
                evt == AddressableAssetSettings.ModificationEvent.EntryRemoved ||
                evt == AddressableAssetSettings.ModificationEvent.EntryMoved ||
                evt == AddressableAssetSettings.ModificationEvent.GroupRemoved)
            {
                EditorApplication.delayCall += RegenerateIfChanged;
            }
        }

        [MenuItem("DDOIT Tools/Scene Switcher/Refresh", priority = 100)]
        private static void ForceRegenerate()
        {
            File.WriteAllText(GENERATED_PATH, BuildCode());
            AssetDatabase.Refresh();
        }

        private static void RegenerateIfChanged()
        {
            string newContent = BuildCode();
            if (File.Exists(GENERATED_PATH) && File.ReadAllText(GENERATED_PATH) == newContent)
                return;

            File.WriteAllText(GENERATED_PATH, newContent);
            AssetDatabase.Refresh();
        }

        private static string BuildCode()
        {
            // DDOIT, InitScene 경로 탐색
            string ddoitPath = FindScenePath(DDOIT_SCENE);
            string initPath = FindScenePath(INIT_SCENE);

            // Addressable 씬 목록 (DDOIT, InitScene 제외)
            var addressableScenes = GetAddressableScenes()
                .Where(p => Path.GetFileNameWithoutExtension(p) != DDOIT_SCENE
                         && Path.GetFileNameWithoutExtension(p) != INIT_SCENE)
                .OrderBy(p => Path.GetFileNameWithoutExtension(p))
                .ToArray();

            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SceneSwitcher. DO NOT EDIT.");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEditor.SceneManagement;");
            sb.AppendLine();
            sb.AppendLine("namespace DDOIT.Tools.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    public static class SceneSwitcherItems");
            sb.AppendLine("    {");

            // DDOIT 씬 — priority 0 (최상단)
            if (ddoitPath != null)
                AppendSceneMenuItem(sb, DDOIT_SCENE, ddoitPath, 0);

            // InitScene — priority 1
            if (initPath != null)
                AppendSceneMenuItem(sb, INIT_SCENE, initPath, 1);

            // Addressable 씬 — priority 12+ (가로선 구분)
            for (int i = 0; i < addressableScenes.Length; i++)
            {
                string name = Path.GetFileNameWithoutExtension(addressableScenes[i]);
                AppendSceneMenuItem(sb, name, addressableScenes[i], 12 + i);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendSceneMenuItem(StringBuilder sb, string sceneName, string scenePath, int priority)
        {
            string method = ToMethodName(sceneName);

            sb.AppendLine();
            sb.AppendLine($"        [MenuItem(\"DDOIT Tools/Scene Switcher/{sceneName}\", priority = {priority})]");
            sb.AppendLine($"        private static void Open_{method}()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())");
            sb.AppendLine($"                EditorSceneManager.OpenScene(\"{scenePath}\", OpenSceneMode.Single);");
            sb.AppendLine("        }");
        }

        private static string FindScenePath(string sceneName)
        {
            var guids = AssetDatabase.FindAssets($"t:Scene {sceneName}");
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (Path.GetFileNameWithoutExtension(path) == sceneName)
                    return path;
            }
            return null;
        }

        private static List<string> GetAddressableScenes()
        {
            var result = new List<string>();
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null) return result;

            foreach (var group in settings.groups)
            {
                if (group == null) continue;
                foreach (var entry in group.entries)
                {
                    if (entry.AssetPath.EndsWith(".unity"))
                        result.Add(entry.AssetPath);
                }
            }

            return result;
        }

        private static string ToMethodName(string sceneName)
        {
            var sb = new StringBuilder(sceneName.Length);
            foreach (char c in sceneName)
            {
                if (char.IsLetterOrDigit(c))
                    sb.Append(c);
                else
                    sb.Append('_');
            }
            return sb.ToString();
        }
    }
}
