// Auto-generated by SceneSwitcher. DO NOT EDIT.
using UnityEditor;
using UnityEditor.SceneManagement;

namespace DDOIT.Tools.Editor
{
    public static class SceneSwitcherItems
    {

        [MenuItem("DDOIT Tools/Scene Switcher/DDOIT", priority = 0)]
        private static void Open_DDOIT()
        {
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                EditorSceneManager.OpenScene("Assets/DDOIT_Tools/Scenes/DDOIT.unity", OpenSceneMode.Single);
        }

        [MenuItem("DDOIT Tools/Scene Switcher/InitScene", priority = 1)]
        private static void Open_InitScene()
        {
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                EditorSceneManager.OpenScene("Assets/DDOIT_Tools/Scenes/InitScene.unity", OpenSceneMode.Single);
        }

        [MenuItem("DDOIT Tools/Scene Switcher/TestSceneA", priority = 12)]
        private static void Open_TestSceneA()
        {
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                EditorSceneManager.OpenScene("Assets/01. Scenes/TestSceneA.unity", OpenSceneMode.Single);
        }

        [MenuItem("DDOIT Tools/Scene Switcher/TestSceneB", priority = 13)]
        private static void Open_TestSceneB()
        {
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                EditorSceneManager.OpenScene("Assets/01. Scenes/TestSceneB.unity", OpenSceneMode.Single);
        }
    }
}
